import { LocalizedTextIdNikisoft } from './localized-text-id.nikisoft';

export function buildLocalizedTextEnNikiSoft() {
   return {
      [LocalizedTextIdNikisoft.Loading]: 'Loading...',
      [LocalizedTextIdNikisoft.Save]: 'Save',
      [LocalizedTextIdNikisoft.Cancel]: 'Cancel',
      [LocalizedTextIdNikisoft.Previous]: 'Previous',
      [LocalizedTextIdNikisoft.Next]: 'Next',
      [LocalizedTextIdNikisoft.LoginButton]: 'Login',
      [LocalizedTextIdNikisoft.LoginTitle]: 'Login',
      [LocalizedTextIdNikisoft.UserName]: 'User name',
      [LocalizedTextIdNikisoft.Password]: 'Password',
      [LocalizedTextIdNikisoft.LogOutButton]: 'Log out',
      [LocalizedTextIdNikisoft.Validation_EmailIncorrectFormat]: 'Format of entered email address is incorrect!',
      [LocalizedTextIdNikisoft.Validation_MaxLength]: 'Maximal length is {{0}} characters!',
      [LocalizedTextIdNikisoft.Validation_MinLength]: 'Minimal length is {{0}} characters!',
      [LocalizedTextIdNikisoft.Validation_MaxValue]: 'Maximum value must be less or equal to {{0}}!',
      [LocalizedTextIdNikisoft.Validation_MinValue]: 'Minimal value must be greater or equal to {{0}}!',
      [LocalizedTextIdNikisoft.Validation_Required]: 'Value is mandatory!',
      [LocalizedTextIdNikisoft.NotFoundTitle]: 'NOT FOUND',
      [LocalizedTextIdNikisoft.NotFoundSubTitle]: 'Sorry, but we haven\'t found what are you looking for!',
      [LocalizedTextIdNikisoft.NoPermissionTitle]: 'PERMISSION NOT GRANTED',
      [LocalizedTextIdNikisoft.NoPermissionSubTitle]: 'Sorry, but you have not been granted permission to access the page!',
      [LocalizedTextIdNikisoft.UnableToConnectToServer]: 'We are unable to connect to server!',
      [LocalizedTextIdNikisoft.UnknownError]: 'An unknown error has occurred!',
      [LocalizedTextIdNikisoft.ServerFailed]: 'An internal server error has occurred!',
      [LocalizedTextIdNikisoft.RequestedServiceNotFound]: 'Requested service was not found on server!',
      [LocalizedTextIdNikisoft.NotAuthorized]: 'You are not authorized to perform the action!',
      [LocalizedTextIdNikisoft.BadUserNameOrPassword]: 'Incorrect user name or password!',
      [LocalizedTextIdNikisoft.QueryFailed]: 'Querying model has failed!',
      [LocalizedTextIdNikisoft.NoPermissionGranted]: 'You have not been granted permission to access the resource!',
      [LocalizedTextIdNikisoft.EditEntityNotFound]: 'Unable to identify the object to be edited!',
      [LocalizedTextIdNikisoft.Name]: 'Name',
      [LocalizedTextIdNikisoft.DeleteTitle]: 'Delete',
      [LocalizedTextIdNikisoft.DeleteMessage]: 'The selected item will be permanently deleted.',
      [LocalizedTextIdNikisoft.Delete]: 'Delete',
      [LocalizedTextIdNikisoft.Modules]: 'Modules',
      [LocalizedTextIdNikisoft.Add]: 'Add',
      [LocalizedTextIdNikisoft.Edit]: 'Edit',
      [LocalizedTextIdNikisoft.Order]: 'Order',
      [LocalizedTextIdNikisoft.OrderAsc]: 'Ascending',
      [LocalizedTextIdNikisoft.OrderDesc]: 'Descending',
      [LocalizedTextIdNikisoft.FirstName]: 'First name',
      [LocalizedTextIdNikisoft.LastName]: 'Last name',
      [LocalizedTextIdNikisoft.Company]: 'Company',
      [LocalizedTextIdNikisoft.Ico]: 'ICO',
      [LocalizedTextIdNikisoft.Street]: 'Street',
      [LocalizedTextIdNikisoft.StreetNo]: 'Street No.',
      [LocalizedTextIdNikisoft.City]: 'City',
      [LocalizedTextIdNikisoft.Zip]: 'ZIP',
      [LocalizedTextIdNikisoft.Phone]: 'Phone number',
      [LocalizedTextIdNikisoft.Email]: 'E-mail',
      [LocalizedTextIdNikisoft.Position]: 'Position',
      [LocalizedTextIdNikisoft.Pin]: 'PIN',
      [LocalizedTextIdNikisoft.BasicInformation]: 'Basic information',
      [LocalizedTextIdNikisoft.AdditionalInformation]: 'Additional information',
      [LocalizedTextIdNikisoft.Monday]: 'Monday',
      [LocalizedTextIdNikisoft.Tuesday]: 'Tuesday',
      [LocalizedTextIdNikisoft.Wednesday]: 'Wednesday',
      [LocalizedTextIdNikisoft.Thursday]: 'Thursday',
      [LocalizedTextIdNikisoft.Friday]: 'Friday',
      [LocalizedTextIdNikisoft.Saturday]: 'Saturday',
      [LocalizedTextIdNikisoft.Sunday]: 'Sunday',
      [LocalizedTextIdNikisoft.StartDateTime]: 'Start date and time',
      [LocalizedTextIdNikisoft.StartDate]: 'Start date',
      [LocalizedTextIdNikisoft.StartTime]: 'Start time',
      [LocalizedTextIdNikisoft.FinishDateTime]: 'Finish date and time',
      [LocalizedTextIdNikisoft.FinishDate]: 'Finish date',
      [LocalizedTextIdNikisoft.FinishTime]: 'Finish time',
      [LocalizedTextIdNikisoft.Date]: 'Date',
      [LocalizedTextIdNikisoft.PickDate]: 'Pick date',
      [LocalizedTextIdNikisoft.List]: 'List',
      [LocalizedTextIdNikisoft.Validation_StartBeforeFinish]: 'Start date and time must be before finish date and time.',
      [LocalizedTextIdNikisoft.Validation_StartFinishSameDate]: 'Start and finish date and time must be on same day.',
      [LocalizedTextIdNikisoft.CalendarMonth_MoveBackward]: 'Load model from previous month',
      [LocalizedTextIdNikisoft.CalendarMonth_MoveToNow]: 'Load model from actual month',
      [LocalizedTextIdNikisoft.CalendarMonth_MoveForward]: 'Load model from next month',
      [LocalizedTextIdNikisoft.CalendarMonth_Refresh]: 'Reload model',
      [LocalizedTextIdNikisoft.ErrorsList]: 'List of errors',
      [LocalizedTextIdNikisoft.Settings]: 'Settings',
      [LocalizedTextIdNikisoft.Year]: 'Year',
      [LocalizedTextIdNikisoft.Item]: 'Item',
      [LocalizedTextIdNikisoft.Value]: 'Value',
   };
}
