import { LocalizedTextIdNikisoft } from './localized-text-id.nikisoft';

export function buildLocalizedTextSkNikiSoft() {
   return {
      [LocalizedTextIdNikisoft.Loading]: 'Načítavam...',
      [LocalizedTextIdNikisoft.Save]: 'Uložiť',
      [LocalizedTextIdNikisoft.Cancel]: 'Zrušiť',
      [LocalizedTextIdNikisoft.Previous]: 'Späť',
      [LocalizedTextIdNikisoft.Next]: 'Ďalej',
      [LocalizedTextIdNikisoft.LoginButton]: 'Prihlásiť',
      [LocalizedTextIdNikisoft.LoginTitle]: 'Prihlásenie',
      [LocalizedTextIdNikisoft.UserName]: 'Meno používateľa',
      [LocalizedTextIdNikisoft.Password]: 'Heslo',
      [LocalizedTextIdNikisoft.LogOutButton]: 'Odhlásiť',
      [LocalizedTextIdNikisoft.Validation_EmailIncorrectFormat]: 'Formát emailu je nesprávny!',
      [LocalizedTextIdNikisoft.Validation_MaxLength]: 'Maximálna dĺžka musí byť {{0}} znakov!',
      [LocalizedTextIdNikisoft.Validation_MinLength]: 'Minimálna dĺžka musí byť {{0}} znakov!',
      [LocalizedTextIdNikisoft.Validation_MaxValue]: 'Maximálna hodnoa nusí byť menšia alebo rovná {{0}}!',
      [LocalizedTextIdNikisoft.Validation_MinValue]: 'Minimálna hodnota musí byť väčšia alebo rovná {{0}}!',
      [LocalizedTextIdNikisoft.Validation_Required]: 'Hodnota je povinná!',
      [LocalizedTextIdNikisoft.NotFoundTitle]: 'STRÁNKA NENÁJDENÁ',
      [LocalizedTextIdNikisoft.NotFoundSubTitle]: 'Bohužial, to čo hľadáte, neexistuje!',
      [LocalizedTextIdNikisoft.NoPermissionTitle]: 'POVOLENIE NEBOLO UDELENÉ',
      [LocalizedTextIdNikisoft.NoPermissionSubTitle]:
         'Bohužial, ale nemáte povolenie na prístup k požadovanej stránke!',
      [LocalizedTextIdNikisoft.UnableToConnectToServer]: 'Nepodarilo sa spojiť so serverom!',
      [LocalizedTextIdNikisoft.UnknownError]: 'Vyskytla sa neznáma chyba!',
      [LocalizedTextIdNikisoft.ServerFailed]: 'Vyskytla sa chyba na serveri!',
      [LocalizedTextIdNikisoft.RequestedServiceNotFound]: 'Požadovaná služba sa nenachádza na serveri!',
      [LocalizedTextIdNikisoft.NotAuthorized]: 'Nemáte oprávnenie na vykonanie tejto akcie!',
      [LocalizedTextIdNikisoft.BadUserNameOrPassword]: 'Zlé používateľské meno alebo heslo!',
      [LocalizedTextIdNikisoft.QueryFailed]: 'Načítavanie údajov zlyhalo!',
      [LocalizedTextIdNikisoft.NoPermissionGranted]: 'Nemáte povolenie na prístup k požadovaným dátam!',
      [LocalizedTextIdNikisoft.EditEntityNotFound]: 'Nie je možné identifikovať údaje pre editáciu!',
      [LocalizedTextIdNikisoft.Name]: 'Názov',
      [LocalizedTextIdNikisoft.DeleteTitle]: 'Mazať',
      [LocalizedTextIdNikisoft.DeleteMessage]: 'Zvolená položka bude permanentne odstránená.',
      [LocalizedTextIdNikisoft.Delete]: 'Zmazať',
      [LocalizedTextIdNikisoft.Modules]: 'Moduly',
      [LocalizedTextIdNikisoft.Add]: 'Pridať',
      [LocalizedTextIdNikisoft.Edit]: 'Upraviť',
      [LocalizedTextIdNikisoft.Order]: 'Zoradiť',
      [LocalizedTextIdNikisoft.OrderAsc]: 'Vzostupne',
      [LocalizedTextIdNikisoft.OrderDesc]: 'Zostupne',
      [LocalizedTextIdNikisoft.FirstName]: 'Krstné meno',
      [LocalizedTextIdNikisoft.LastName]: 'Priezvisko',
      [LocalizedTextIdNikisoft.Company]: 'Spoločnosť',
      [LocalizedTextIdNikisoft.Ico]: 'IČO',
      [LocalizedTextIdNikisoft.Street]: 'Ulica',
      [LocalizedTextIdNikisoft.StreetNo]: 'Číslo ulice',
      [LocalizedTextIdNikisoft.City]: 'Mesto',
      [LocalizedTextIdNikisoft.Zip]: 'PSČ',
      [LocalizedTextIdNikisoft.Phone]: 'Telefonné číslo',
      [LocalizedTextIdNikisoft.Email]: 'Emailová adresa',
      [LocalizedTextIdNikisoft.Position]: 'Pozícia',
      [LocalizedTextIdNikisoft.Pin]: 'PIN',
      [LocalizedTextIdNikisoft.BasicInformation]: 'Základné informácie',
      [LocalizedTextIdNikisoft.AdditionalInformation]: 'Doplnkové informácie',
      [LocalizedTextIdNikisoft.StartDateTime]: 'Dátum a čas začiatku',
      [LocalizedTextIdNikisoft.StartDate]: 'Dátum začiatku',
      [LocalizedTextIdNikisoft.StartTime]: 'Čas začiatku',
      [LocalizedTextIdNikisoft.FinishDateTime]: 'Dátum a čas konca',
      [LocalizedTextIdNikisoft.FinishDate]: 'Dátum konca',
      [LocalizedTextIdNikisoft.FinishTime]: 'Čas konca',
      [LocalizedTextIdNikisoft.Date]: 'Dátum',
      [LocalizedTextIdNikisoft.PickDate]: 'Vybrať dátum',
      [LocalizedTextIdNikisoft.List]: 'Zoznam',
      [LocalizedTextIdNikisoft.Validation_StartBeforeFinish]:
         'Dátum a čas začiatku musí byť pred dátumom a časom konca.',
      [LocalizedTextIdNikisoft.Validation_StartFinishSameDate]: 'Dátum začiatku a konca musí byť v ten istý deň.',
      [LocalizedTextIdNikisoft.CalendarMonth_MoveBackward]: 'Ísť na prechadzajúci mesiac',
      [LocalizedTextIdNikisoft.CalendarMonth_MoveToNow]: 'Ísť na aktuálny mesiac',
      [LocalizedTextIdNikisoft.CalendarMonth_MoveForward]: 'Ísť na nasledujúci mesiac',
      [LocalizedTextIdNikisoft.CalendarMonth_Refresh]: 'Obnoviť',
      [LocalizedTextIdNikisoft.ErrorsList]: 'Zoznam chýb',
      [LocalizedTextIdNikisoft.Settings]: 'Nastavenia',
      [LocalizedTextIdNikisoft.Setting]: 'Nastavenie',
      [LocalizedTextIdNikisoft.Year]: 'Rok',
      [LocalizedTextIdNikisoft.Item]: 'Položka',
      [LocalizedTextIdNikisoft.Value]: 'Hodnota',
      [LocalizedTextIdNikisoft.Details]: 'Detaily',
      [LocalizedTextIdNikisoft.Version]: 'Verzia',
      [LocalizedTextIdNikisoft.GoToHomePage]: 'Vrátiť sa domovskú stránku',
   };
}
